import { describe,it,expect } from 'vitest';
import { createGame,act,available,model,defaultActivities,selected,projectCost,forkDecision,indicatorValue,sdgImpact,coherence,welfare } from './engine';
import { scenarios,scenarioById } from '../data/scenarios';
import { decode } from './storage';
import type { GameState } from './types';
export function prepare(id='agua',alt='a1',seed='PROY-4831',studies=true){let g=createGame(id,'guiado',seed);if(studies)for(const st of scenarioById(id).studies)g=act(g,{type:'study',id:st.id});g=act(g,{type:'nodes',ids:['n0','n1','n2','n3','n4']});g=act(g,{type:'mga',section:'links',value:{...g.mga!,links:[{from:'n2',to:'n1'},{from:'n1',to:'n0'},{from:'n0',to:'n3'},{from:'n3',to:'n4'}]}});g=act(g,{type:'actor',id:'actor0',choice:'consultar'});g=act(g,{type:'actor',id:'actor1',choice:'consultar'});g=act(g,{type:'next'});g=act(g,{type:'objective',id:'n0'});g=act(g,{type:'alternative',id:alt});g=act(g,{type:'next'});g=act(g,{type:'activities',value:defaultActivities(g)});g=act(g,{type:'indicators',value:[{name:'Acceso efectivo',kind:'Resultado',baseline:0,target:g.target,unit:'personas',frequency:'Trimestral',source:'Registro simulado',owner:'Planeación',measure:'coverage'}]});g=act(g,{type:'mga',section:'chain',value:{...g.mga!,chain:{cause:'n1',objective:'n1',product:'service',activities:g.activities.map(a=>a.id)}}});if(projectCost(g)>available(g))g=act(g,{type:'finance',source:'credito'});g=act(g,{type:'next'});g=act(g,{type:'ack',id:'evaluation'});g=act(g,{type:'next'});g=act(g,{type:'policy',id:'none',failure:'Ninguna falla suficiente'});g=act(g,{type:'alignment',sdgs:scenarioById(id).sdgs,policy:true});g=act(g,{type:'next'});return g;}
export function complete(initial:GameState,choice:'continuar'|'mitigar'='mitigar'){let g=initial.snapshot?initial:act(initial,{type:'commit'});for(let i=0;i<100&&!g.outcome;i++){try{g=act(g,g.pendingEvent?{type:'respond',choice}:{type:'advance'});}catch{g=act(g,!g.loans.some(l=>l.type==='credito')?{type:'finance',source:'credito'}:{type:'abandon'});}expect(available(g)).toBeGreaterThanOrEqual(-.001);const s=scenarioById(g.scenarioId);expect(g.cash+g.spent).toBeCloseTo(s.budget+g.loans.reduce((n,l)=>n+l.principal,0)+(g.grantReceived?s.budget*.2:0),5);}return g;}
describe('Partidas completas',()=>{
 for(const s of scenarios)it(s.title+' tiene inicio, decisiones y cierre reproducible',()=>{const g=complete(prepare(s.id));expect(g.outcome).not.toBeNull();expect(g.phase).toBe(7);expect(g.outcome!.score).toBeGreaterThanOrEqual(0);expect(g.outcome!.score).toBeLessThanOrEqual(100);expect(g.outcome!.alternatives).toHaveLength(4);expect(g.committed).toBe(0);expect(Number.isFinite(g.outcome!.financial)).toBe(true);const same=complete(prepare(s.id));expect(same.outcome).toEqual(g.outcome);});
 it('genera trayectorias distintas con distintas decisiones',()=>{const a=complete(prepare('agua','a1')),b=complete(prepare('agua','a2'));expect(a.outcome!.financial).not.toBe(b.outcome!.financial);expect(a.outcome!.coverage).not.toBe(b.outcome!.coverage)});
 it('abandonar antes de invertir no imputa una obra inexistente',()=>{let g=createGame('agua');g=act(g,{type:'study',id:'demanda'});g=act(g,{type:'abandon'});expect(g.outcome!.financial).toBe(-456);expect(g.outcome!.coverage).toBe(0);expect(g.outcome!.score).toBeLessThan(40)});
 it('puede haber valor financiero negativo y valor social positivo',()=>{const m=model(prepare('agua','a2'));expect(m.financial.npv).toBeLessThan(0);expect(m.social.npv).toBeGreaterThan(0)});
 it('una mala cadena causal reduce el beneficio social',()=>{const g=prepare('planta','a0');const bad={...g,nodes:['n0','d1','d2'],objective:'d1'};expect(coherence(bad)).toBeLessThan(coherence(g));expect(model(bad).social.npv).toBeLessThan(model(g).social.npv);});
});
describe('Invariantes y persistencia',()=>{
 it('un gasto fallido no cambia recursos ni historial',()=>{const g={...createGame('agua'),cash:1};expect(()=>act(g,{type:'study',id:'tecnico'})).toThrow('Saldo insuficiente');expect(g.cash).toBe(1);expect(g.journal).toHaveLength(0)});
 it('los estudios cuestan tiempo, revelan sin modificar la realidad y no se duplican',()=>{const base=createGame('agua'),g=act(base,{type:'study',id:'demanda'});expect(g.quality).toBeGreaterThan(base.quality);expect(g.month).toBe(2);expect(g.truth).toEqual(base.truth);expect(()=>act(g,{type:'study',id:'demanda'})).toThrow();});
 it('reservas no se gastan por el mero paso de la obra',()=>{let g=act(prepare(),{type:'commit'});g=act(g,{type:'advance'});if(g.pendingEvent)g=act(g,{type:'respond',choice:'continuar'});g=act(g,{type:'advance'});expect(g.committed).toBeGreaterThanOrEqual(g.budget.operation+g.budget.maintenance+g.budget.contingency-.001)});
 it('recargar conserva exactamente eventos y decisiones',()=>{let g=act(prepare(),{type:'commit'});g=act(g,{type:'advance'});const restored=decode(JSON.stringify({version:1,active:g,history:[]})).active!;expect(restored).toEqual(g);const action=g.pendingEvent?{type:'respond' as const,choice:'continuar' as const}:{type:'advance' as const};expect(act(restored,action)).toEqual(act(g,action));expect(()=>decode('{invalid')).toThrow();});
 it('no permite saltar etapas ni modificar una inversión comprometida',()=>{expect(()=>act(createGame('agua'),{type:'alternative',id:'a0'})).toThrow();const g=act(prepare(),{type:'commit'});expect(()=>act(g,{type:'budget',value:g.budget})).toThrow();});
 it('cofinanciación tiene requisitos y demora, crédito tiene servicio de deuda',()=>{let g=prepare();g=act(g,{type:'finance',source:'cofinanciacion'});const cash=g.cash;for(let i=0;i<3;i++)g=act(g,{type:'waitGrant'});expect(g.cash).toBe(cash);g=act(g,{type:'waitGrant'});expect(g.cash).toBe(cash+7600);expect(()=>act(g,{type:'finance',source:'cofinanciacion'})).toThrow();const loan=act(g,{type:'finance',source:'credito'});expect(model(loan).rows[1].equity).toBeLessThan(model(g).rows[1].equity);});
 it('la meta no fabrica el valor observado de un indicador',()=>{const g=prepare(),ind=g.indicators[0];expect(indicatorValue(g,ind)).toBe(indicatorValue(g,{...ind,target:9999999}));});
 it('mantenimiento insuficiente y asignación incompleta afectan el servicio',()=>{const g=prepare(),bad={...g,budget:{...g.budget,maintenance:0},activities:g.activities.map(a=>({...a,cost:a.cost*.3}))};expect(model(bad,selected(bad),true).coverage).toBeLessThan(model(g,selected(g),true).coverage)});
 it('la semilla se mantiene entre dificultades, pero cambia información',()=>{const a=createGame('agua','guiado','X'),b=createGame('agua','experto','X');expect(a.truth).toEqual(b.truth);expect(a.quality).toBeGreaterThan(b.quality)});
 it('flujos reales y nominales dan el mismo VPN incluso con retraso',()=>{const g=prepare();const a=model(g,selected(g),false,{delay:12,nominal:false}),b=model(g,selected(g),false,{delay:12,nominal:true});expect(a.financial.npv).toBeCloseTo(b.financial.npv,6);expect(a.social.npv).toBeCloseTo(b.social.npv,6)});
 it('la exploración conserva fecha, dinero y resultado original',()=>{const g=complete(prepare()),before=JSON.stringify(g);let fork=forkDecision(g);expect(fork.seed).toBe(g.seed);expect(fork.month).toBe(g.snapshot!.month);expect(fork.cash).toBe(g.snapshot!.decisionState!.cash);fork=act(fork,{type:'next'});expect(fork.month).toBe(g.snapshot!.month);expect(JSON.stringify(g)).toBe(before)});
 it('regulación conserva participaciones y registra costos y ODS causales',()=>{const g=prepare();expect(welfare(g,'targeted').shares.reduce((a,b)=>a+b,0)).toBeCloseTo(100);expect(welfare(g,'strict').admin).toBeGreaterThan(0);expect(welfare(g,'none').total).not.toBe(welfare(g,'strict').total);expect(sdgImpact({...g,performance:0},6)).toBe(0);expect(sdgImpact(g,17)).toBe(0)});
});

describe('Expansión de Aurora',()=>{
 it('ofrece nueve proyectos completos y eventos identificables',()=>{expect(scenarios).toHaveLength(9);for(const s of scenarios){expect(s.alternatives).toHaveLength(4);expect(s.events).toHaveLength(8);expect(new Set(s.events.map(e=>e.id)).size).toBe(8);}});
 it('consultar respuestas no modifica la partida y produce consecuencias diferentes',()=>{const g=act(prepare('energia'),{type:'commit'});g.pendingEvent={...scenarios.find(s=>s.id==='energia')!.events.find(e=>e.id==='convoy')!};const original=JSON.stringify(g);const a=act(g,{type:'respond',choice:'continuar'},false),b=act(g,{type:'respond',choice:'redimensionar'},false);expect(JSON.stringify(g)).toBe(original);expect(a.extraCost).toBeGreaterThan(b.extraCost);expect(a.performance).toBeGreaterThan(b.performance);expect(a.pendingEvent).toBeNull();});
 it('conserva partidas anteriores sin introducirles los eventos nuevos',()=>{const g=prepare('agua');g.contentVersion=1;expect(decode(JSON.stringify({version:1,active:g,history:[]})).active!.contentVersion).toBe(1);const done=complete(g);expect(done.eventIds.some(id=>['convoy','brigada','repuestos','asamblea'].includes(id))).toBe(false);});
});

// Estas pruebas verifican consecuencias académicas, no solo presencia de campos.
describe('Laboratorio MGA',()=>{
 it('requiere conectar el argumento en partidas nuevas',()=>{let g=createGame('agua');g=act(g,{type:'nodes',ids:['n0','n1','n2','n3','n4']});expect(()=>act(g,{type:'next'})).toThrow('laboratorio MGA');g.contentVersion=2;expect(act(g,{type:'next'}).phase).toBe(1);});
 it('las flechas y la clasificación del producto afectan coherencia y beneficio social',()=>{const good=prepare();const wrong={...good,mga:{...good.mga!,links:good.mga!.links.map(l=>({from:l.to,to:l.from})),chain:{...good.mga!.chain,product:'population'}}};expect(coherence(wrong)).toBeLessThan(coherence(good));expect(model(wrong).social.npv).toBeLessThan(model(good).social.npv);expect(model(wrong).financial.npv).toBe(model(good).financial.npv);});
 it('rechaza enlaces duplicados sin alterar recursos',()=>{const g=prepare(),before=JSON.stringify(g);const initial={...g,phase:0,snapshot:null};expect(()=>act(initial,{type:'mga',section:'links',value:{...g.mga!,links:[{from:'n1',to:'n0'},{from:'n1',to:'n0'}]}})).toThrow('duplicados');expect(JSON.stringify(g)).toBe(before);});
 it('no puntúa automáticamente hipótesis ni reflexiones',()=>{const g=prepare();expect(coherence({...g,mga:{...g.mga!,prediction:'Una hipótesis distinta',assumption:'Otro supuesto'}})).toBe(coherence(g));const end=complete(g),saved=act(end,{type:'reflection',text:'La cobertura cayó porque…'});expect(saved.outcome).toEqual(end.outcome);expect(saved.cash).toBe(end.cash);expect(saved.mga!.reflection).toContain('cobertura');expect(decode(JSON.stringify({version:1,active:saved,history:[saved]})).active!.mga).toEqual(saved.mga);});
 it('la cadena detecta actividades eliminadas después de confirmar',()=>{const g=prepare(),bad={...g,activities:[]};expect(coherence(bad)).toBeLessThan(coherence(g));});
});
