import type {MgaDossier} from './mga';
export type PlayerRole = 'publico' | 'privado';
export type Difficulty = 'guiado' | 'profesional' | 'experto';
export const phases = ['Diagnóstico','Formulación','Preparación','Evaluación','Regulación','Decisión','Ejecución','Ex post'] as const;
export interface Alternative { id:string; name:string; description:string; capex:number; opex:number; revenue:number; social:number; coverage:number; months:number; life:number; risk:number; equity:number; environment:number; complexity:number; acceptance:number; flexibility:number; causes:string[]; product:string; tradeoff:string; sdg:Record<number,number>; }
export interface Study {id:string;name:string;cost:number;months:number;quality:number;reveals:'demand'|'technical'|'environment'|'social';finding:string}
export interface Stakeholder {id:string;name:string;power:number;interest:number;position:number;affected:string;contribution:string;resources:number}
export interface Risk {id:string;name:string;category:string;probability:number;impact:number;cost:number;mitigation:string;owner:string;study:string}
/** Execution event. Conditions and probability modifiers are declarative data evaluated like the dilemmas' ones. */
export interface GameEvent {minVersion?:number;id:string;name:string;description:string;category:string;probability:number;cost:number;delay:number;benefit:number;study:string;conditions?:import('../data/dilemmas').DilemmaCondition;modifiers?:{when:import('../data/dilemmas').DilemmaCondition;factor:number}[]}
export interface PolicyInstrument {id:string;name:string;description:string;admin:number;compliance:number;benefit:number;price:number;externality:number;entry:number;distribution:string;failure:string}
export interface LogicNode {id:string;label:string;objective:string;valid:boolean;parent?:string;level:'central'|'direct'|'indirect'|'effect'|'impact'}
export interface Scenario {/** Generated missions: the author's remaining causes and effects, offered as cards of the problem tree. */treeExtras?:{label:string;level:'direct'|'indirect'|'effect'|'impact'}[];id:string;version:number;title:string;sector:string;role:PlayerRole;regulator?:boolean;territory:string;brief:string;population:number;affected:number;budget:number;deadline:number;demand:number;supply:number;unit:string;failure:string;constraints:string[];nodes:LogicNode[];alternatives:Alternative[];studies:Study[];actors:Stakeholder[];risks:Risk[];events:GameEvent[];instruments:PolicyInstrument[];sdgs:number[];policy:number;market:number[];demandIntercept:number;supplyIntercept:number;externalCost:number}
export interface FinancialModel {capex:number;opex:number;revenue:number;growth:number;inflation:number;life:number;residual:number;discount:number;nominal:boolean}
export interface EconomicModel {annualBenefit:number;externality:number;shadowCost:number;discount:number}
export interface Assumptions {demand:number;capex:number;opex:number;price:number;growth:number;inflation:number;discount:number;socialDiscount:number;life:number;residual:number;nominal:boolean;delay:number}
export interface Budget {operation:number;maintenance:number;environment:number;social:number;oversight:number;contingency:number}
export interface Indicator {name:string;kind:'Gestión'|'Producto'|'Resultado'|'Impacto';baseline:number;target:number;unit:string;frequency:string;source:string;owner:string;measure?:'coverage'|'progress'|'spending'|'benefit'}
export interface Activity {id:string;name:string;months:number;dependency:string;cost:number;owner:string}
export interface Decision {id:number;month:number;phase:number;title:string;detail:string;cost:number;time:number;justification?:string}
export interface Loan {principal:number;rate:number;years:number;type:'credito'|'socio'}
export interface Snapshot {alternative:string;assumptions:Assumptions;budget:Budget;policy:string;causes:string[];objective:string;target:number;available:number;month:number;quality:number;support:number;coherence:number;expectedFinancial:number;expectedSocial:number;loans:Loan[];mitigations:string[];sdgs:number[];policyAligned:boolean;activities:Activity[];indicators:Indicator[];decisionState?:GameState}
/** One scored activity of the game inside a dimension of the final grade. */
export interface ScorePart {name:string;value:number;share:number}
export interface Outcome {assessment?:import('./scoringV2').AssessmentV2;status:'completado'|'incumplimiento'|'insolvencia'|'abandonado';score:number;dimensions:{name:string;value:number;weight:number;/** Activities that make up the dimension: value 0–100 and share of the dimension (shares add up to 1). */parts?:ScorePart[]}[];financial:number;social:number;coverage:number;expectedFinancial:number;expectedSocial:number;opportunity:number;expectedOpportunity:number;best:string;alternatives:{name:string;expected:number;realized:number;feasible:boolean}[];wasted:number;lessons:string[]}
export interface GameState {v2?:import('./projectV2').V2State;learning?:import('./learning').LearningAttempt[];mga?:MgaDossier;version:1;contentVersion:number;id:string;scenarioId:string;seed:string;difficulty:Difficulty;phase:number;maxPhase:number;month:number;elapsed:number;cash:number;committed:number;spent:number;quality:number;capacity:number;support:number;reputation:number;sustainability:number;studies:string[];actorActions:Record<string,string>;nodes:string[];objective:string;target:number;alternative:string;compared:string[];budget:Budget;assumptions:Assumptions;loans:Loan[];grantPending:number;grantReceived:boolean;policy:string;failure:string;mitigations:string[];sdgs:number[];policyAligned:boolean;indicators:Indicator[];activities:Activity[];journal:Decision[];justification:string;truth:{demand:number;technical:number;environment:number};performance:number;extraCost:number;delay:number;pendingEvent:GameEvent|null;eventIds:string[];snapshot:Snapshot|null;outcome:Outcome|null;returnPhase:number|null;acknowledged:string[]}
