import {useEffect,useRef} from 'react';
import {flushSync} from 'react-dom';
import type {GameState} from './types';
import {available,type Action} from './engine';
export function publicStatus(g:GameState|null){return g?{scenario:g.scenarioId,phase:g.phase,month:g.month,available:available(g),committed:g.committed,information:g.quality,alternative:g.alternative,event:g.pendingEvent?{title:g.pendingEvent.name,description:g.pendingEvent.description}:null,finished:!!g.outcome,score:g.outcome?.score}: {phase:'home'};}
interface ModelContext {registerTool(tool:{name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown},options:{signal:AbortSignal}):void|Promise<void>}
export function useWebMCP(g:GameState|null,send:(action:Action)=>unknown){const state=useRef({g,send});state.current={g,send};useEffect(()=>{const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const empty={type:'object',properties:{},additionalProperties:false};const validate=(input:unknown)=>{if(input===null||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Se requiere un objeto vacío.');};
 const tools=[{name:'read_simulation_status',title:'Consultar la simulación',description:'Lee etapa, recursos e información visible. No revela condiciones ocultas ni cambia la partida.',inputSchema:empty,annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input:unknown)=>{validate(input);return publicStatus(state.current.g)}},{name:'advance_execution',title:'Avanzar la ejecución',description:'Avanza hasta tres meses en la ejecución y desembolsa recursos simulados comprometidos. Solo funciona en ejecución sin evento pendiente. Usa el mismo motor que el botón visible.',inputSchema:empty,annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{validate(input);const g=state.current.g;if(!g||g.phase!==6||g.pendingEvent||g.outcome)throw new Error('La partida no permite avanzar ejecución ahora.');let result:unknown;flushSync(()=>{result=state.current.send({type:'advance'})});return {result,status:publicStatus(state.current.g)}}}];
 for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{/* Unsupported implementations do not affect the game. */}}
 return ()=>lifecycle.abort();},[]);}
