import NegotiationDesk from './NegotiationDesk';
import { useState } from 'react';
import {useDraftGuard,different} from '../components/workbench';
import type { GameState } from '../domain/types';
import type { Action } from '../domain/engine';
import { estimate, available } from '../domain/engine';
import { scenarioById } from '../data/scenarios';
import { money, number } from '../domain/finance';
import { Panel,Button,Range,Tip,Metric,Chart } from '../components/ui';
import { Check, Search, ArrowDown, Users, Clock } from 'lucide-react';
export default function Diagnosis({g,send}:{g:GameState;send:(a:Action)=>void}){
 const s=scenarioById(g.scenarioId),[target,setTarget]=useState(g.target),[growth,setGrowth]=useState(.02),[nodes,setNodes]=useState(g.nodes);
 useDraftGuard(target!==g.target||different(nodes,g.nodes));
 return <><Panel className="brief-panel" kicker="EL ENCARGO" title={s.territory}><p className="brief">{s.brief}</p><div className="metric-grid"><Metric label="Población de referencia" value={number(s.population)}/><Metric label="Población afectada" value={number(s.affected)}/><Metric label="Recursos iniciales" value={'$ '+money(g.v2?.initialCash??s.budget)} sub="Millones de COP"/></div><div className="constraint-row">{s.constraints.map(c=><span key={c}>{c}</span>)}</div></Panel>
 <Panel title="La información también tiene un precio" kicker="01 / INVESTIGA"><p className="muted">Puedes invertir en conocer el problema o decidir con lo que sabes. Ningún estudio elimina toda la incertidumbre.</p><div className="study-grid">{s.studies.map(st=>{const bought=g.studies.includes(st.id);return <article className={'study '+(bought?'purchased':'')} key={st.id}><div className="study-title"><Search size={19}/><h4>{st.name}</h4>{bought&&<Check size={18}/>}</div><p>{bought?st.finding:'Revela '+({demand:'demanda e intervalo esperado',technical:'restricciones y costos técnicos',environment:'condiciones ambientales y permisos',social:'barreras de acceso y aceptación'}[st.reveals])+'.'}</p><div className="study-price"><strong>$ {money(st.cost)}</strong><span><Clock size={13}/> {st.months} meses</span></div><Button secondary onClick={()=>send({type:'study',id:st.id})} disabled={bought||st.cost>available(g)}>{bought?'Estudio incorporado':'Contratar estudio'}{!bought&&<span>+{st.quality} información</span>}</Button></article>})}</div><div className="information-box"><span>Demanda esperada · {s.unit}</span><strong>{g.studies.includes('demanda')?number(s.demand*estimate(g,'demand')):'Información por precisar'}</strong><small>{g.studies.includes('demanda')?`Intervalo: ${number(s.demand*estimate(g,'demand')*.84)} – ${number(s.demand*estimate(g,'demand')*1.16)} · confianza orientativa: ${g.quality} %`:`Referencia preliminar: ${number(s.demand)}; variación posible ± ${g.difficulty==='experto'?40:30} %.`}</small></div></Panel>
 <Panel title="Construye el árbol del problema" kicker="02 / CONECTA LAS CAUSAS"><p className="muted">Selecciona las tarjetas que explican el problema. Su posición define la relación causal; una relación elegida no implica que sea válida.</p><div className="problem-tree">{(['impact','effect','central','direct','indirect'] as const).map((level,i)=><div key={level}><div className="tree-label">{['Efectos indirectos','Efectos directos','Problema central','Causas directas','Causas indirectas'][i]}</div><div className="tree-row">{s.nodes.filter(n=>n.level===level).map(n=><button key={n.id} aria-pressed={nodes.includes(n.id)} className={'tree-node '+(nodes.includes(n.id)?'chosen':'')} disabled={n.id==='n0'} onClick={()=>setNodes(nodes.includes(n.id)?nodes.filter(id=>id!==n.id):[...nodes,n.id])}>{n.label}{nodes.includes(n.id)&&<Check size={15}/>}</button>)}</div>{i<4&&<ArrowDown className="tree-arrow" size={18}/>}</div>)}</div><Button secondary onClick={()=>send({type:'nodes',ids:nodes})}>Confirmar relaciones</Button><Tip title="Problema, causa y solución">Describe una situación negativa verificable. La ausencia de una obra concreta no demuestra por sí misma cuál es el problema. Las causas deben explicar el problema y las causas indirectas deben explicar las directas.</Tip></Panel>
 <Panel title="¿A quién vas a priorizar?" kicker="03 / FOCALIZA"><Range label="Población objetivo" min={Math.ceil(s.affected*.25)} max={s.affected} step={Math.max(1,Math.round(s.affected/100))} value={target} onChange={setTarget} format={number}/><div className="coverage-map">{Array.from({length:20},(_,i)=><div key={i} className={i<target/s.affected*20?'covered':''}><Users size={19}/></div>)}</div><div className="metric-grid"><Metric label="Objetivo / afectada" value={Math.round(target/s.affected*100)+' %'}/><Metric label="No priorizada" value={number(s.affected-target)}/><Metric label="Beneficiarios directos" value="Según alternativa" sub="La cobertura efectiva se calcula después"/></div><Button secondary onClick={()=>send({type:'target',value:target})}>Confirmar focalización</Button><Tip title="Cobertura y equidad">La población objetivo es el grupo priorizado dentro de la población afectada. Los beneficiarios directos son quienes reciben el servicio; los indirectos reciben efectos secundarios. Este mapa es esquemático, no representa geografía oficial.</Tip><Range label="Crecimiento exploratorio de demanda anual" min={0} max={.08} step={.005} value={growth} onChange={setGrowth} format={v=>(v*100).toFixed(1)+' %'}/><Chart data={Array.from({length:6},(_,y)=>({name:'Año '+y,demanda:Math.round(s.demand*estimate(g,'demand')*(1+growth)**y),oferta:s.supply}))} series={[{key:'demanda',name:'Demanda estimada',color:'#377864'},{key:'oferta',name:'Oferta existente',color:'#b79657'}]}/></Panel>
 {g.v2&&<ActorBuilder g={g} send={send}/>}<Panel title="Nadie ejecuta un proyecto a solas" kicker="04 / ACTORES"><div className="stakeholder-matrix"><span className="axis-y">PODER →</span><span className="axis-x">INTERÉS →</span><span className="quadrant q1">Mantener satisfechos</span><span className="quadrant q2">Gestionar de cerca</span><span className="quadrant q3">Monitorear</span><span className="quadrant q4">Mantener informados</span>{s.actors.map((a,i)=>(!g.v2||g.v2.actorMap[a.id])&&<span className="actor-dot" key={a.id} style={{left:(g.v2?(g.v2.actorMap[a.id]?.interest==='alto'?72:25):10+a.interest*.75)+'%',bottom:(g.v2?(g.v2.actorMap[a.id]?.power==='alto'?72:25):10+a.power*.7)+'%'}} title={a.name}>{i+1}</span>)}</div><div className="actors-list">{s.actors.map((a,i)=><article key={a.id}><div className="actor-heading"><span className="avatar">{i+1}</span><div><h4>{a.name}</h4><p>{a.position<0?'Posición inicial: cautelosa':'Posición inicial: favorable'} · Poder {a.power}/100 · Interés {a.interest}/100</p></div></div><p className="muted">Afectación: {a.affected}. Aporta: {a.contribution}. Recursos: {a.resources}/100; bloqueo potencial: {a.power>=80?'alto':'medio'}.</p>{g.actorActions[a.id]?<span className="badge">Decisión: {g.actorActions[a.id]}</span>:<div className="actor-actions">{[['consultar','Consultar · 1 mes'],['negociar','Negociar · 2 meses'],['informar','Informar'],['involucrar','Involucrar · 3 meses'],['monitorear','Monitorear'],['ignorar','Ignorar']].map(([key,name])=><button className="chip" key={key} onClick={()=>send({type:'actor',id:a.id,choice:key})}>{name}<small>{({consultar:.003,negociar:.008,informar:.001,involucrar:.012,monitorear:.0005,ignorar:0} as Record<string,number>)[key]*s.budget} M</small></button>)}</div>}</article>)}</div></Panel>{g.v2&&<NegotiationDesk g={g} send={send}/>}</>;
}


import {ActorBuilder} from './BuildersV2';
