import { useState } from 'react';
import {useDraftGuard} from '../components/workbench';
import { ResponsiveContainer,RadarChart,PolarGrid,PolarAngleAxis,Radar,Legend } from 'recharts';
import { ArrowRight,Check } from 'lucide-react';
import type { GameState } from '../domain/types';
import { model,type Action } from '../domain/engine';
import { scenarioById } from '../data/scenarios';
import { money } from '../domain/finance';
import { Panel,Button,Tip,Chart } from '../components/ui';
export default function Formulation({g,send}:{g:GameState;send:(a:Action)=>void}){const s=scenarioById(g.scenarioId),[objective,setObjective]=useState(g.objective);const compared=s.alternatives.filter(a=>g.compared.includes(a.id)),colors=['#377864','#b79657','#737ba4'];const radar=['Cobertura','Equidad','Ambiente','Flexibilidad','Aceptación'].map((name,i)=>({name,...Object.fromEntries(compared.map(a=>[a.id,[a.coverage*100,a.equity,50+a.environment/2,a.flexibility,a.acceptance][i]]))}));useDraftGuard(objective!==g.objective);return <>
 <Panel title="Del problema a una situación deseada" kicker="01 / ÁRBOL DE OBJETIVOS"><p className="muted">Transforma las situaciones seleccionadas en medios y fines. Elige cuál debe ser el objetivo central.</p><div className="objective-tree">{s.nodes.filter(n=>g.nodes.includes(n.id)).map(n=><div className="objective-row" key={n.id}><span>{n.label}</span><ArrowRight size={18}/><button className={'objective-card '+(objective===n.id?'chosen':'')} aria-pressed={objective===n.id} onClick={()=>setObjective(n.id)}>{n.objective}{objective===n.id&&<Check size={16}/>}</button></div>)}</div><Button onClick={()=>send({type:'objective',id:objective})} disabled={!objective} secondary>Confirmar objetivo central</Button></Panel>
 <Panel title="Cuatro caminos. Distintos compromisos." kicker="02 / ALTERNATIVAS"><p className="muted">Selecciona una propuesta y compara hasta tres alternativas. Los valores son estimaciones; la inversión cambia con tu población objetivo.</p><div className="alternative-grid">{s.alternatives.map((a,i)=><article key={a.id} className={'alternative '+(g.alternative===a.id?'chosen':'')}><div className="alternative-top"><span className="alternative-letter">{String.fromCharCode(65+i)}</span><label className="checkline"><input type="checkbox" checked={g.compared.includes(a.id)} disabled={!g.compared.includes(a.id)&&g.compared.length>=3} onChange={e=>send({type:'compare',ids:e.target.checked?[...g.compared,a.id]:g.compared.filter(id=>id!==a.id)})}/>Comparar</label></div><h3>{a.name}</h3><p>{a.description}</p><div className="alt-metrics"><div><span>Inversión base</span><strong>$ {money(a.capex)}</strong></div><div><span>Cobertura máxima</span><strong>{Math.round(a.coverage*100)} %</strong></div><div><span>Construcción</span><strong>{a.months} meses</strong></div><div><span>OPEX anual</span><strong>$ {money(a.opex)}</strong></div></div><p className="tradeoff">{a.tradeoff}</p><Button secondary={g.alternative!==a.id} onClick={()=>send({type:'alternative',id:a.id})} disabled={g.alternative===a.id}>{g.alternative===a.id?'Propuesta seleccionada':'Seleccionar propuesta'}{g.alternative===a.id&&<Check size={16}/>}</Button></article>)}</div></Panel>
 {compared.length>0&&<Panel title="Compara sin perder de vista el problema" kicker="03 / EVIDENCIA"><div className="two-col"><div className="chart" style={{height:320}}><ResponsiveContainer><RadarChart data={radar}><PolarGrid/><PolarAngleAxis dataKey="name" tick={{fontSize:12}}/>{compared.map((a,i)=><Radar key={a.id} dataKey={a.id} name={a.name} stroke={colors[i]} fill={colors[i]} fillOpacity={.12}/>)}<Legend wrapperStyle={{fontSize:12}}/></RadarChart></ResponsiveContainer></div><Chart bar data={compared.map(a=>{const m=model(g,a);return {name:a.name,financiero:m.financial.npv,social:m.social.npv}})} series={[{key:'financiero',name:'VPN financiero · M COP',color:'#b79657'},{key:'social',name:'VPN social · M COP',color:'#377864'}]} height={320}/></div><div className="table-wrap"><table><thead><tr><th>Alternativa</th><th>B/C financiera</th><th>Riesgo técnico</th><th>Complejidad</th><th>Aceptación</th></tr></thead><tbody>{compared.map(a=><tr key={a.id}><td>{a.name}</td><td>{model(g,a).financial.bc?.toFixed(2)}</td><td>{a.risk}/100</td><td>{a.complexity}/100</td><td>{a.acceptance}/100</td></tr>)}</tbody></table></div><Tip title="La rentabilidad no decide por ti">Un VPN alto no garantiza que el proyecto atienda las causas elegidas. Compara también cobertura, equidad, capacidad de ejecución y efectos no monetizados. Este comparador usa los supuestos y partidas presupuestales actuales para todas las alternativas.</Tip></Panel>}
 </>}
