import {type BudgetLine,validBudgetLines,lineTotal} from '../domain/budgetLines';
import BudgetCalculator from './BudgetCalculator';
import { useState } from 'react';
import {useDraftGuard,different} from '../components/workbench';
import type { GameState,Budget,Indicator,Activity } from '../domain/types';
import { available,selected,projectCost,schedule,defaultActivities,technicalBudget,type Action } from '../domain/engine';
import { scenarioById } from '../data/scenarios';
import { money,number } from '../domain/finance';
import { Panel,Field,Button,Metric,Tip } from '../components/ui';
import { ArrowRight,Plus,Trash2 } from 'lucide-react';
export const budgetLabels:Record<keyof Budget,string>={operation:'Reserva de operación',maintenance:'Mantenimiento anual',environment:'Gestión ambiental',social:'Gestión social',oversight:'Interventoría',contingency:'Contingencias'};
export function Finance({g,send}:{g:GameState;send:(a:Action)=>void}){const s=scenarioById(g.scenarioId);return <Panel title="El capital tiene condiciones" kicker="FINANCIACIÓN"><div className="finance-grid"><article><h4>Crédito a cinco años</h4><strong>$ {money(s.budget*.35)}</strong><p>12 % efectivo anual. Cinco cuotas iguales, desde el primer año tras la inversión; un retraso no suspende pagos. Reduce el flujo disponible para el financiador del proyecto.</p><Button secondary disabled={!!g.v2?.challenge?.noCredit||g.loans.some(l=>l.type==='credito')} onClick={()=>send({type:'finance',source:'credito'})}>{g.v2?.challenge?.noCredit?'No disponible en este reto':g.loans.some(l=>l.type==='credito')?'Crédito contratado':'Contratar crédito'}</Button></article>{s.role==='publico'?<article><h4>Cofinanciación condicionada</h4><strong>$ {money(s.budget*.2)}</strong><p>Desembolso en cuatro meses. Requiere apoyo ≥ 60 y priorizar ≥ 70 % de la población afectada. No cuenta como caja hasta recibirla.</p><Button secondary disabled={g.grantReceived||!!g.grantPending} onClick={()=>send({type:'finance',source:'cofinanciacion'})}>{g.grantReceived?'Aporte recibido':g.grantPending?'Desembolso: mes '+g.grantPending:'Solicitar aporte'}</Button></article>:<article><h4>Socio inversor</h4><strong>$ {money(s.budget*.25)}</strong><p>Recibe 25 % de los flujos positivos a lo largo de la vida del proyecto. Comparte capital y retorno.</p><Button secondary disabled={g.loans.some(l=>l.type==='socio')} onClick={()=>send({type:'finance',source:'socio'})}>Incorporar socio</Button></article>}</div>{g.grantPending>0&&g.phase!==6&&<div className="actions"><Button secondary onClick={()=>send({type:'waitGrant'})}>Esperar un mes al desembolso</Button><span className="muted">Esperar también consume plazo.</span></div>}</Panel>}
export default function Preparation({g,send}:{g:GameState;send:(a:Action)=>void}){const s=scenarioById(g.scenarioId),a=selected(g)!,[budget,setBudget]=useState(g.budget),[lines,setLines]=useState<BudgetLine[]>(g.v2?.budgetLines??[]),[indicators,setIndicators]=useState<Indicator[]>(g.indicators.length?g.indicators:[{name:'Personas con acceso efectivo',kind:'Resultado',baseline:0,target:Math.round(g.target*a.coverage),unit:'personas',measure:'coverage',frequency:'Trimestral',source:'Registro operativo simulado',owner:'Equipo de seguimiento'}]),[activities,setActivities]=useState<Activity[]>(g.activities.length?g.activities:g.v2?defaultActivities(g).map(a=>({...a,cost:0})):defaultActivities(g));const preview={...g,budget};const cost=projectCost(preview),timeline=schedule(activities);
 useDraftGuard(different(budget,g.budget)||different(lines,g.v2?.budgetLines??[]));useDraftGuard(different(indicators,g.indicators));useDraftGuard(different(activities,g.activities));
 return <>{g.v2?<ChainBuilder g={g} send={send}/>:<Panel title="Conecta recursos con resultados" kicker="01 / CADENA DE VALOR"><div className="value-chain">{[['Insumos','Capital, equipo y conocimiento'],['Actividades',activities.map(v=>v.name).join(' · ')],['Productos',a.product],['Resultados',s.nodes.find(n=>n.id===g.objective)?.objective||'Objetivo por definir'],['Impactos',s.nodes.find(n=>n.id==='n4')!.objective]].map(([label,value],i)=><div key={label}><span>{label}</span><strong>{value}</strong>{i<4&&<ArrowRight size={18}/>}</div>)}</div><Tip title="El cuello de botella de la operación">Construir capacidad sin financiar operación, mantenimiento o adopción reduce el servicio efectivo. La reserva operativa respalda caja; no se suma dos veces al costo anual del flujo.</Tip></Panel>}
 <Panel title="Distribuye recursos escasos" kicker="02 / PRESUPUESTO"><div className="metric-grid"><Metric label="Saldo libre" value={'$ '+money(available(g))}/><Metric label="Propuesta a comprometer" value={'$ '+money(cost)}/><Metric label="Saldo después de comprometer" value={'$ '+money(available(g)-cost)}/></div><div className="budget-bar">{Object.entries(budget).map(([key,v],i)=><span key={key} title={budgetLabels[key as keyof Budget]+': '+money(v)} style={{width:v/Math.max(cost,1)*100+'%',background:['#477b69','#76a28f','#a4bb9e','#bca66f','#81989e','#d6c79b'][i]}}/>)}</div><p className="muted">Inversión técnica: $ {money(technicalBudget(g))} · Preinversión ya pagada: $ {money(g.spent)} · Todos los valores en millones de COP.</p><div className="field-grid">{Object.entries(budgetLabels).map(([key,label])=><Field key={key} label={label}><input type="number" min={0} step={50} value={budget[key as keyof Budget]} onChange={e=>setBudget({...budget,[key]:Number(e.target.value)})}/></Field>)}</div>{g.v2&&<BudgetCalculator labels={budgetLabels} budget={budget} lines={lines} onAdd={line=>{setLines([...lines,line]);setBudget(prev=>({...prev,[line.category]:prev[line.category]+lineTotal(line)}))}} onRemove={id=>{const line=lines.find(l=>l.id===id)!;setLines(lines.filter(l=>l.id!==id));setBudget(prev=>({...prev,[line.category]:Math.max(0,prev[line.category]-lineTotal(line))}))}}/>}<Button disabled={!!g.v2&&!validBudgetLines(lines,budget)} onClick={()=>send({type:'budget',value:budget,...(g.v2?{lines}:{})})}>Confirmar asignación</Button></Panel>
 <Finance g={g} send={send}/>
 <Panel title="Un cronograma que reconoce dependencias" kicker="03 / PROGRAMACIÓN"><div className="table-wrap"><table><thead><tr><th>Actividad</th><th>Meses</th><th>Depende de</th><th>Costo M</th><th>Responsable</th><th/></tr></thead><tbody>{activities.map((v,i)=><tr key={v.id}><td><input aria-label={'Actividad '+(i+1)} value={v.name} onChange={e=>setActivities(activities.map((a,j)=>j===i?{...a,name:e.target.value}:a))}/></td><td><input aria-label={'Duración '+(i+1)} type="number" min={1} max={60} value={v.months} onChange={e=>setActivities(activities.map((a,j)=>j===i?{...a,months:Number(e.target.value)}:a))}/></td><td><select aria-label={'Dependencia '+(i+1)} value={v.dependency} onChange={e=>setActivities(activities.map((a,j)=>j===i?{...a,dependency:e.target.value}:a))}><option value="">Sin dependencia</option>{activities.slice(0,i).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></td><td><input aria-label={'Costo '+(i+1)} type="number" min={0} value={v.cost} onChange={e=>setActivities(activities.map((a,j)=>j===i?{...a,cost:Number(e.target.value)}:a))}/></td><td><input aria-label={'Responsable '+(i+1)} value={v.owner} onChange={e=>setActivities(activities.map((a,j)=>j===i?{...a,owner:e.target.value}:a))}/></td><td><button className="icon-btn" aria-label="Eliminar actividad" onClick={()=>setActivities(activities.filter(a=>a.id!==v.id).map(a=>a.dependency===v.id?{...a,dependency:''}:a))}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div><div className="gantt">{timeline.rows.map(a=><div className="gantt-row" key={a.id}><span>{a.name}</span><div><div style={{marginLeft:a.start/Math.max(1,timeline.duration)*100+'%',width:a.months/Math.max(1,timeline.duration)*100+'%'}}>{a.start}–{a.end}</div></div></div>)}</div><p className="muted">Ruta programada: {timeline.duration} meses. El mínimo técnico de la alternativa es {a.months} meses. Costos asignados: $ {money(activities.reduce((n,a)=>n+a.cost,0))}.</p><div className="actions"><Button secondary onClick={()=>setActivities([...activities,{id:'act'+Date.now(),name:'Nueva actividad',months:2,dependency:activities.at(-1)?.id||'',cost:0,owner:'Equipo ejecutor'}])}><Plus size={16}/>Agregar actividad</Button><Button onClick={()=>send({type:'activities',value:activities})}>Confirmar cronograma</Button></div></Panel>
 <Panel title="Define qué significará avanzar" kicker="04 / INDICADORES"><p className="muted">Distingue realizar actividades de producir cambios en la población. Define metas verificables y una fuente.</p>{indicators.map((ind,i)=><div className="indicator-editor" key={i}><div className="field-grid">{(['name','unit','source','owner'] as const).map((key,j)=><Field key={key} label={['Nombre','Unidad','Fuente','Responsable'][j]}><input value={ind[key]} onChange={e=>setIndicators(indicators.map((v,k)=>k===i?{...v,[key]:e.target.value}:v))}/></Field>)}<Field label="Medida observada"><select value={ind.measure??'coverage'} onChange={e=>{const measure=e.target.value as Indicator['measure'];const units={coverage:'personas',progress:'%',spending:'M COP',benefit:'M COP / año'};setIndicators(indicators.map((v,k)=>k===i?{...v,measure,unit:units[measure!]}:v))}}><option value="coverage">Personas con acceso efectivo</option><option value="progress">Avance físico (%)</option><option value="spending">Gasto ejecutado (M COP)</option><option value="benefit">Beneficio social anual (M COP)</option></select></Field><Field label="Tipo"><select value={ind.kind} onChange={e=>setIndicators(indicators.map((v,k)=>k===i?{...v,kind:e.target.value as Indicator['kind']}:v))}>{['Gestión','Producto','Resultado','Impacto'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Periodicidad"><select value={ind.frequency} onChange={e=>setIndicators(indicators.map((v,k)=>k===i?{...v,frequency:e.target.value}:v))}>{['Mensual','Trimestral','Anual'].map(v=><option key={v}>{v}</option>)}</select></Field>{(['baseline','target'] as const).map(key=><Field key={key} label={key==='baseline'?'Línea base':'Meta'}><input type="number" value={ind[key]} onChange={e=>setIndicators(indicators.map((v,k)=>k===i?{...v,[key]:Number(e.target.value)}:v))}/></Field>)}</div><button className="text-btn" onClick={()=>setIndicators(indicators.filter((_,k)=>k!==i))}>Eliminar indicador</button></div>)}<div className="actions"><Button secondary onClick={()=>setIndicators([...indicators,{name:'',kind:'Producto',baseline:0,target:100,unit:'%',measure:'progress',frequency:'Trimestral',source:'Registro simulado',owner:'Equipo de seguimiento'}])}>Agregar indicador</Button><Button onClick={()=>send({type:'indicators',value:indicators})}>Confirmar indicadores</Button></div><p className="muted">Población objetivo: {number(g.target)}. Los valores observados se simulan durante la ejecución.</p></Panel></>}




import {ChainBuilder} from './BuildersV2';
