import { useState } from 'react';
import {useDraftGuard,different} from '../components/workbench';
import type { GameState } from '../domain/types';
import { welfare,selected,type Action } from '../domain/engine';
import { scenarioById } from '../data/scenarios';
import { sdgs } from '../data/sdgs';
import policies from '../data/policyFrameworks.json';
import { money } from '../domain/finance';
import { Panel,Field,Button,Metric,Tip,Chart } from '../components/ui';
export function Risks({g,send}:{g:GameState;send:(a:Action)=>void}){const s=scenarioById(g.scenarioId);return <Panel title="Gestiona lo que puede salir distinto" kicker="RIESGOS"><div className="risk-heatmap">{Array.from({length:25},(_,i)=>{const prob=i%5+1,impact=5-Math.floor(i/5);return <div key={i} style={{background:`hsl(${130-prob*impact*4.6} 35% ${94-prob*impact*.9}%)`}}><small>{prob} × {impact}</small>{s.risks.filter(r=>Math.ceil(r.probability*(g.studies.includes(r.study)?.65:1)*(g.mitigations.includes(r.id)?.5:1)/20)===prob&&Math.ceil(r.impact/20)===impact).map(r=><span key={r.id}>{r.id.toUpperCase()}</span>)}</div>})}</div><div className="axis-caption">Probabilidad → · Impacto ↑ · Escala 1–5</div>{s.risks.map(r=><article className="risk-row" key={r.id}><div><h4>{r.id.toUpperCase()} · {r.name}</h4><p>{r.category} · Responsable: {r.owner}</p><p className="muted">{r.mitigation}. Probabilidad residual: {Math.round(r.probability*(g.studies.includes(r.study)?.65:1)*(g.mitigations.includes(r.id)?.5:1))} % · Impacto: {r.impact}/100.</p></div><Button secondary onClick={()=>send({type:'mitigate',id:r.id})} disabled={g.mitigations.includes(r.id)}>{g.mitigations.includes(r.id)?'Mitigación activa':'Mitigar · $ '+money(r.cost)}</Button></article>)}<Tip title="Riesgo residual">Probabilidad e impacto son estimaciones configuradas por escenario. Estudios y mitigaciones reducen exposición, sin garantizar que un evento no ocurra. Estas medidas también consumen recursos.</Tip></Panel>}
export default function Regulation({g,send}:{g:GameState;send:(a:Action)=>void}){const s=scenarioById(g.scenarioId),a=selected(g)!,[failure,setFailure]=useState(g.failure),[policy,setPolicy]=useState(g.policy),[aligned,setAligned]=useState(g.sdgs),[pnd,setPnd]=useState(g.policyAligned);const w=welfare(g,policy);useDraftGuard(policy!==g.policy||failure!==g.failure);useDraftGuard(different(aligned,g.sdgs)||pnd!==g.policyAligned);return <>
 <Panel title={s.role==='privado'?'Anticipa regulación y externalidades':'Intervenir también tiene un costo'} kicker="01 / ANÁLISIS DE IMPACTO REGULATORIO"><p className="muted">{s.role==='privado'?'Como empresa, eliges una estrategia de cumplimiento y adaptación. No tienes autoridad para dictar regulación.':'Identifica el problema de mercado y compara la intervención con mantener el escenario base.'}</p><Field label="Falla que justifica la decisión"><select value={failure} onChange={e=>setFailure(e.target.value)}><option value="">Selecciona tu diagnóstico</option>{['Ninguna falla suficiente','Externalidades','Bienes públicos','Recursos comunes','Información asimétrica','Selección adversa','Riesgo moral','Poder de mercado','Monopolio natural','Barreras de entrada','Problemas de coordinación'].map(v=><option key={v}>{v}</option>)}</select></Field><div className="instrument-grid">{s.instruments.map(p=><button key={p.id} className={'instrument '+(policy===p.id?'chosen':'')} aria-pressed={policy===p.id} onClick={()=>setPolicy(p.id)}><h4>{p.name}</h4><p>{p.description}</p><strong>Administración: $ {money(p.admin)}</strong><small>Cumplimiento: +{Math.round(p.compliance*100)} % OPEX</small><p className="muted">{p.distribution}</p></button>)}</div><div className="table-wrap"><table><thead><tr><th>Instrumento</th><th>Bienestar neto*</th><th>Administración*</th><th>Cumplimiento*</th><th>Riesgo</th></tr></thead><tbody>{s.instruments.map(p=>{const v=welfare(g,p.id);return <tr key={p.id}><td>{p.name}</td><td>{v.total.toFixed(0)}</td><td>{v.admin.toFixed(0)}</td><td>{v.compliance.toFixed(0)}</td><td>{p.entry<0?'Barreras y captura':p.entry>0?'Fiscalización insuficiente':'Persistencia de la falla'}</td></tr>})}</tbody></table></div><p className="muted">* Índice de bienestar en unidades educativas normalizadas, separado de los flujos del proyecto.</p><Button onClick={()=>send({type:'policy',id:policy,failure})} disabled={!failure}>Confirmar estrategia regulatoria</Button></Panel>
 <Panel title="Precio, acceso y distribución" kicker="02 / BIENESTAR Y ESTRUCTURA"><div className="metric-grid"><Metric label="HHI simulado" value={w.hhi.toFixed(0)}/><Metric label="Empresas" value={w.shares.length}/><Metric label="Bienestar neto*" value={w.total.toFixed(0)}/></div><div className="two-col"><Chart data={Array.from({length:7},(_,i)=>({name:String(i*30),demanda:Math.max(0,s.demandIntercept-i*18),oferta:s.supplyIntercept+i*18,precio:w.price}))} series={[{key:'demanda',name:'Demanda inversa',color:'#377864'},{key:'oferta',name:'Oferta inversa',color:'#b79657'},{key:'precio',name:'Precio simulado',color:'#828bab'}]}/><Chart bar data={w.shares.map((share,i)=>({name:'Empresa '+(i+1),share}))} series={[{key:'share',name:'Participación %',color:'#708d83'}]}/></div><div className="metric-grid compact"><Metric label="Excedente consumidor" value={w.consumer.toFixed(0)}/><Metric label="Excedente productor" value={w.producer.toFixed(0)}/><Metric label="Daño externo" value={w.external.toFixed(0)}/><Metric label="Pérdida de eficiencia" value={w.dwl.toFixed(0)}/></div><Tip title="Modelo regulatorio simplificado">Demanda inversa = 140 − 0,6Q; oferta inversa = 20 + 0,6Q. HHI = suma de participaciones porcentuales al cuadrado. Entrada y consolidación ilustran incentivos; el modelo no predice fusiones ni aplica umbrales legales. Estos instrumentos no recaudan impuestos: recaudo fiscal = 0.</Tip><Tip title="Captura y principal–agente">Un incumbente puede proponer estándares que también bloqueen competidores. Evalúa costos, evidencia y capacidad de fiscalización. Ni más regulación ni menos regulación garantizan mayor bienestar.</Tip></Panel>
 <Risks g={g} send={send}/>{g.v2&&<RegulatoryPuzzle g={g} send={send}/>}
 <Panel title="Contribuir requiere una relación causal" kicker="03 / ODS Y ALINEACIÓN"><p className="muted">Selecciona los ODS que puedes sostener con productos e indicadores. {!g.v2&&<>Este escenario relaciona especialmente {s.sdgs.map(id=>'ODS '+id).join(', ')}.</>}</p><div className="sdg-grid">{sdgs.map(d=><button key={d.id} className={'sdg '+(aligned.includes(d.id)?'chosen':'')} onClick={()=>setAligned(aligned.includes(d.id)?aligned.filter(id=>id!==d.id):[...aligned,d.id])} aria-pressed={aligned.includes(d.id)}><span>{String(d.id).padStart(2,'0')}</span><strong>{d.name}</strong></button>)}</div>{(!g.v2||Object.keys(g.v2.sdgReasons).length>0)&&<div className="table-wrap"><table><thead><tr><th>ODS relevante</th><th>Impacto potencial</th><th>Relación con el proyecto</th></tr></thead><tbody>{s.sdgs.map(id=><tr key={id}><td>{id} · {sdgs[id-1].name}</td><td><span className={'impact-tag '+(a.sdg[id]<0?'negative':'')}>{a.sdg[id]>0?'+':''}{a.sdg[id]}</span></td><td>{a.sdg[id]<0?'La presión ambiental de la alternativa puede contrarrestar sus beneficios.':`${a.product} contribuye mediante cobertura y ${id===10?'priorización de población excluida':'mejora del servicio'}.`} La magnitud final depende del desempeño y la coherencia.</td></tr>)}</tbody></table></div>}<div className="policy-frame"><span className="badge">MARCO HISTÓRICO · {policies[0].period}</span><h4>{policies[0].name}</h4><p>{policies[0].transformations[s.policy]}</p><label className="checkline"><input type="checkbox" checked={pnd} onChange={e=>setPnd(e.target.checked)}/>Mi cadena de valor e indicadores sustentan esta relación.</label><p className="muted">Marco territorial: {policies[1].name}. No se atribuyen programas a planes oficiales actuales.</p><a href={policies[0].source!} target="_blank" rel="noreferrer">Consultar referencia oficial del DNP ↗</a></div><Button onClick={()=>send({type:'alignment',sdgs:aligned,policy:pnd})}>Confirmar alineación</Button><Tip title="ODS y sostenibilidad">Seleccionar una casilla no crea impacto. Los efectos se ponderan por cobertura, ejecución y coherencia causal, y se reportan con indicadores físicos. Una contribución positiva en un objetivo puede coexistir con daño en otro.</Tip></Panel>
 {g.v2&&<SDGBuilder g={g} send={send}/>}</>}


import {SDGBuilder} from './BuildersV2';
import RegulatoryPuzzle from './RegulatoryPuzzle';
