import {useEffect,useRef,useState} from 'react';
import {moodFor,moodLabel,roleFor,type Mood} from '../domain/characters';
import {Radio,ChevronRight,MessageCircle} from 'lucide-react';
import type {GameState} from '../domain/types';
import {assets,crew,dialogue,missions} from '../data/world';
import {scenarioById} from '../data/scenarios';
import {Button} from './ui';
export function Advisor({g}:{g:GameState}){const [person,setPerson]=useState<'mara'|'ivo'>(missions[g.scenarioId].character),[question,setQuestion]=useState('');const member=crew[person];const prev=useRef<GameState|undefined>(undefined),[mood,setMood]=useState<Mood>(()=>moodFor(g));useEffect(()=>{const m=moodFor(g,prev.current);prev.current=g;setMood(m);if(m==='speaking'||m==='positive'){const t=setTimeout(()=>setMood(moodFor(g)),4000);return ()=>clearTimeout(t)}},[g]);const role=roleFor(g.phase);return <section className={'advisor-card mood-'+mood} data-mood={mood}><div className="radio-label"><Radio size={13}/>CANAL DE RECONSTRUCCIÓN<span>EN LÍNEA</span></div><div className="advisor-portrait"><span className="character-frame"><img src={member.image} alt={member.name+', '+member.role}/>{mood==='thinking'&&<i className="thinking-dots" aria-hidden><b/><b/><b/></i>}{mood==='celebrating'&&<i className="celebrate-burst" aria-hidden/>}</span><div><h3>{member.name}</h3><span>{member.role}</span><span className="character-role" role="status">{role} · {moodLabel[mood]}</span></div></div><div className="advisor-speech" key={g.phase+':'+g.journal.length+':'+person}><MessageCircle size={16}/><p>{dialogue(g,person)}</p></div><div className="crew-switch">{(['mara','ivo'] as const).map(id=><button key={id} className={person===id?'selected':''} onClick={()=>{setPerson(id);setQuestion('')}}><img src={crew[id].image} alt=""/>{crew[id].name}</button>)}</div><details className="ask-advisor"><summary>Consultar al equipo</summary>{[['prioridad','¿Qué debo decidir ahora?'],['riesgo','¿Qué sacrificamos?']].map(([id,text])=><button key={id} onClick={()=>setQuestion(id)}>{text}<ChevronRight size={14}/></button>)}{question&&<p>{question==='prioridad'?['Construye el árbol del problema, decide cuánta información comprar y a quién priorizar.','Transforma el problema en un objetivo y elige una propuesta entre las alternativas.','Confirma presupuesto, actividades e indicadores. Asegura financiación antes de gastar.','Revisa flujos y sensibilidad. Confirma los supuestos que realmente usarás.','Diagnostica la falla, compara instrumentos y sustenta los ODS con tu cadena de valor.','Revisa lo que comprometes y explica tu criterio. Después empieza la ejecución.','Responde al evento pendiente o avanza al siguiente periodo.','Compara lo esperado con lo observado y prueba otra estrategia.'][g.phase]:'Cada recurso usado aquí deja de estar disponible para otra necesidad. Mira quién recibe el beneficio, quién asume el costo y qué incertidumbre permanece.'}</p>}</details><small className="scripted-note">Personajes narrativos · respuestas locales</small></section>}
export function MissionBriefing({g,onAccept}:{g:GameState;onAccept:()=>void}){const mission=missions[g.scenarioId],s=scenarioById(g.scenarioId);return <div className="mission-briefing"><div className="briefing-scene"><img src={assets.nation} alt="La nación de Aurora en reconstrucción"/><span>TRANSMISIÓN DEL CONSEJO · {mission.district.toUpperCase()}</span></div><div className="briefing-message"><img src={crew[mission.character].image} alt={crew[mission.character].name}/><div><span>{crew[mission.character].name} · mensaje de campo</span><h3>{mission.chapter}</h3><p>{mission.hook}</p><p className="muted">{mission.stakes}</p></div></div><div className="mission-objectives"><strong>Tu encargo</strong><p>{s.nodes[0].objective}. Completa diagnóstico, propuesta y ejecución. Puedes equivocarte, adaptarte y volver a intentarlo.</p></div><Button onClick={onAccept}>Recibir el encargo <ChevronRight size={16}/></Button></div>}
