import type { ReactNode } from 'react';
import { Info, ArrowRight } from 'lucide-react';
import { ResponsiveContainer, CartesianGrid, XAxis, YAxis, Tooltip, Legend, LineChart, Line, BarChart, Bar } from 'recharts';
export function Panel({title,kicker,children,className=''}:{title?:string;kicker?:string;children:ReactNode;className?:string}){return <section className={'panel '+className}>{kicker&&<div className="eyebrow">{kicker}</div>}{title&&<h3>{title}</h3>}{children}</section>}
export function Tip({title,children}:{title:string;children:ReactNode}){return <details className="tip"><summary><Info size={15}/>{title} <span>¿Por qué importa?</span></summary><div>{children}</div></details>}
export function Button({children,onClick,secondary=false,disabled=false,type='button'}:{children:ReactNode;onClick?:()=>void;secondary?:boolean;disabled?:boolean;type?:'button'|'submit'}){return <button type={type} onClick={onClick} disabled={disabled} className={secondary?'btn secondary':'btn'}>{children}</button>}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function Range({label,value,onChange,min,max,step=1,format}:{label:string;value:number;onChange:(n:number)=>void;min:number;max:number;step?:number;format?:(n:number)=>string}){return <Field label={label}><div className="range-value"><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><output>{format?format(value):value}</output></div></Field>}
export function Metric({label,value,sub}:{label:string;value:ReactNode;sub?:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
export function Next({onClick,label='Guardar y avanzar'}:{onClick:()=>void;label?:string}){return <div className="next-row"><span>Tus decisiones cambian el siguiente paso.</span><Button onClick={onClick}>{label}<ArrowRight size={17}/></Button></div>}
export function Chart({data,series,bar=false,height=260}:{data:Record<string,unknown>[];series:{key:string;name:string;color:string}[];bar?:boolean;height?:number}){const C=bar?BarChart:LineChart;return <div className="chart" style={{height}}><ResponsiveContainer width="100%" height="100%"><C data={data} margin={{top:10,right:10,left:0,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e1e8e3"/><XAxis dataKey="name" tick={{fontSize:12}}/><YAxis tick={{fontSize:12}} width={62}/><Tooltip contentStyle={{borderRadius:10,border:'1px solid #dce4df',fontSize:13}} formatter={(v:unknown)=>typeof v==='number'?v.toLocaleString('es-CO',{maximumFractionDigits:1}):String(v)}/><Legend wrapperStyle={{fontSize:12}}/>{series.map(s=>bar?<Bar key={s.key} dataKey={s.key} name={s.name} fill={s.color} radius={[3,3,0,0]}/>:<Line key={s.key} type="monotone" dataKey={s.key} name={s.name} stroke={s.color} strokeWidth={2.5} dot={false}/>)}</C></ResponsiveContainer></div>}
