import type { SheetData } from "../domain/project/import/xlsxWriter";

/** Text of a fictitious project document (PDF test and E2E). */
export const pdfPages: string[][] = [
  [
    "Ficha del proyecto",
    "Nombre del proyecto: Mercado campesino de Los Álamos",
    "Sector: Desarrollo rural",
    "Ubicación: Los Álamos (municipio ficticio)",
    "Problema central: Bajos ingresos de los productores campesinos por intermediación excesiva",
    "Causas",
    "- Falta de un espacio de comercialización directa con condiciones sanitarias",
    "- Débil organización de los productores",
    "Efectos",
    "- Pérdida de ingresos de los hogares rurales",
    "- Migración de jóvenes a la ciudad",
    "Objetivo general: Aumentar los ingresos de los productores campesinos",
    "Objetivos específicos",
    "1. Disponer de un espacio de comercialización directa",
    "2. Fortalecer la organización de los productores",
  ],
  [
    "Población afectada: 4.800 productores",
    "Población objetivo: 3.200 productores",
    "Horizonte: 10 años",
    "Tasa de descuento: 12 %",
    "Presupuesto: $ 3.500 millones",
    "Alternativa 1: Plaza de mercado cubierta",
    "Inversión: 2.400 millones",
    "Operación y mantenimiento: 150 millones",
    "Ingresos anuales: 90 millones",
    "Duración: 12 meses",
    "Vida útil: 20 años",
    "Cobertura: 80 %",
    "Alternativa 2: Mercado móvil itinerante",
    "Inversión: 900 millones",
    "Operación y mantenimiento: 210 millones",
    "Duración: 4 meses",
    "Vida útil: 8 años",
    "Cobertura: 45 %",
    "Falla de mercado: Poder de mercado de los intermediarios",
    "ODS: 1, 2 y 8",
  ],
];
/** Workbook of a fictitious project (Excel test and E2E). */
export const excelSheets: SheetData[] = [
  {
    name: "Proyecto",
    rows: [
      ["Campo", "Valor"],
      ["Nombre del proyecto", "Biblioteca rural de San Roque"],
      ["Sector", "Educación y cultura"],
      ["Ubicación", "San Roque (municipio ficticio)"],
      ["Problema central", "Bajo acceso a lectura y conectividad de estudiantes rurales"],
      ["Objetivo general", "Aumentar el acceso a lectura y conectividad de estudiantes rurales"],
      ["Población total", 25000],
      ["Población afectada", 6000],
      ["Población objetivo", 4500],
      ["Horizonte", 12],
      ["Tasa de descuento", 0.1],
      ["Tasa social de descuento", "9 %"],
      ["Presupuesto", 2600],
      ["Falla de mercado", "Bienes públicos"],
      ["ODS", "4, 9, 10"],
    ],
  },
  {
    name: "Árbol",
    rows: [
      ["Tipo", "Descripción", "Nivel"],
      ["Causa", "Distancia a bibliotecas y centros culturales", "Directa"],
      ["Causa", "Baja cobertura de internet en veredas", "Indirecta"],
      ["Efecto", "Bajo rendimiento escolar", "Directo"],
      ["Efecto", "Menores oportunidades de empleo juvenil", "Indirecto"],
      ["Objetivo específico", "Acercar servicios de lectura a las veredas", ""],
      ["Objetivo específico", "Ampliar la conectividad en veredas", ""],
    ],
  },
  {
    name: "Alternativas",
    rows: [
      ["Alternativa", "Descripción", "Inversión (M)", "O&M anual (M)", "Ingresos anuales (M)", "Beneficio social anual (M)", "Duración (meses)", "Vida útil (años)", "Valor residual (M)", "Cobertura (%)"],
      ["Biblioteca central con wifi", "Edificio en la cabecera", 1800, 140, 10, 420, 14, 25, 700, "70 %"],
      ["Bibliotecas satélite", "Cinco puntos veredales", 1300, 190, 0, 380, 8, 12, 150, 0.85],
    ],
  },
  { name: "Actores", rows: [["Actor", "Interés", "Poder (0-100)", "Posición (-100 a 100)"], ["Secretaría de Educación", "Cobertura", 80, 50], ["Juntas de padres", "Acceso", 40, 70]] },
  { name: "Costos", rows: [["Rubro", "Tipo", "Monto (M)"], ["Construcción", "Inversión", 1200], ["Bibliotecarios", "Operación", 90]] },
  { name: "Riesgos", rows: [["Riesgo", "Probabilidad", "Impacto", "Mitigación"], ["Baja asistencia", "Media", "Alta", "Programación con colegios"]] },
];
