import {ChallengeCatalog,ChallengeStatus} from './features/Challenges';
import type {Challenge} from './domain/challenges';
import {updateCampaign,campaignSummary} from './domain/recognition';
import ResourceDeck from './components/ResourceDeck';
import {announceExperience,decisionMoment} from './domain/experience';
import MgaLab from './features/MgaLab';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowRight,ArrowLeft,Menu,X,Home,BookOpen,History,ChevronRight,AlertTriangle,PanelLeftClose,PanelLeftOpen } from 'lucide-react';
import type { GameState,Difficulty } from './domain/types';
import { phases } from './domain/types';
import { act,available,selected,riskLevel,forkDecision,type Action } from './domain/engine';
import { scenarios,scenarioById } from './data/scenarios';
import { money } from './domain/finance';
import { load,save,emptySave,type SaveData } from './domain/storage';
import {useWebMCP} from './domain/webmcp';
import { Button,Panel,Field,Next } from './components/ui';
import {DraftProvider,StageGuide,SectionNavigator} from './components/workbench';
import Diagnosis from './features/Diagnosis';
import Formulation from './features/Formulation';
import Preparation from './features/Preparation';
import Evaluation from './features/Evaluation';
import Regulation from './features/Regulation';
import { Decision,Execution,Results,Journal } from './features/Endgame';
import NationHome from './features/NationHome';
import {Advisor,MissionBriefing} from './components/Characters';
import {missions} from './data/world';

const headings=['Entiende antes de intervenir.','Construye una respuesta posible.','Haz viable tu propuesta.','Pon a prueba tus supuestos.','Evalúa las reglas del juego.','Decide con lo que sabes.','Adapta, ejecuta y aprende.','Cada resultado cuenta una historia.'];
const guidance=['Investigar consume recursos, pero puede evitar decisiones costosas. Conecta causas y efectos antes de proponer una solución.','Un objetivo expresa el cambio deseado. Compara lo que ganas y lo que sacrificas con cada alternativa.','Reservar mantenimiento reduce el dinero para construir, pero sostiene el servicio futuro. Revisa también dependencias.','Observa qué supuesto altera más el resultado. Una rentabilidad positiva no asegura resolver el problema.','Compara siempre con no intervenir. Una medida puede mejorar acceso y al mismo tiempo elevar barreras.','Revisa recursos, plazo y supuestos. Tu justificación permitirá discutir la decisión con la información que tenías.','No todos los eventos se pueden evitar. Valora el costo de adaptarte frente a continuar o abandonar.','Distingue calidad de razonamiento, desempeño y condiciones externas. Experimenta con otra estrategia.'];
function initial(){const store=loadStore();activateStore(store);try{return {data:load(),store,error:''}}catch{return {data:structuredClone(emptySave),store,error:'No se pudo leer la partida guardada. Al guardar una partida nueva se intentará conservar una copia del almacenamiento ilegible.'}}}
function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:ReactNode;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const el=ref.current;el?.showModal();return ()=>el?.close()},[]);return <dialog ref={ref} className={'modal '+(wide?'wide':'')} onCancel={onClose} aria-label={title}><button className="modal-close icon-btn" aria-label="Cerrar" onClick={onClose}><X/></button><h2>{title}</h2>{children}</dialog>}

export default function App(){const [boot]=useState(initial),[data,setData]=useState<SaveData>(boot.data),[view,setView]=useState<'home'|'game'|'history'|'help'|'exam'|'projects'|'builder'|'import'>('home'),[setup,setSetup]=useState<string|null>(null),[difficulty,setDifficulty]=useState<Difficulty>('guiado'),[seed,setSeed]=useState(()=> 'PROY-'+Math.floor(1000+Math.random()*9000)),[role,setRole]=useState('todos'),[error,setError]=useState(boot.error),[storageError,setStorageError]=useState(''),[menu,setMenu]=useState(false),[stagesHidden,setStagesHidden]=useState(readStagesHidden),[journal,setJournal]=useState(false),[reopen,setReopen]=useState<number|null>(null),[abandon,setAbandon]=useState(false),[historyGame,setHistoryGame]=useState<GameState|null>(null);
 const [mode,setMode]=useState<'aprendizaje'|'evaluacion'>('aprendizaje'),[learn,setLearn]=useState<string|null>(null);
 const [store,setStore]=useState<ProjectStore>(boot.store),[editing,setEditing]=useState<string|null>(null),[savedAt,setSavedAt]=useState('sin cambios'),[resetOpen,setResetOpen]=useState(false);
 function persistStore(next:ProjectStore){setStore(next);try{saveStore(next);setSavedAt(new Date().toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit',second:'2-digit'}))}catch{setStorageError('No se pudo guardar el proyecto en este navegador. Mantén esta pestaña abierta.')}}
 function openBuilder(p:NormalizedProject){persistStore(upsertProject(store,p));setEditing(p.id);setView('builder');window.scrollTo(0,0)}
 function generate(p:NormalizedProject,config:MissionConfig){const res=createMission(store,{...p,metadata:{...p.metadata,status:'listo'}},config);if(!res.ok)return 'No se pudo generar la partida: '+res.errors.map(e=>typeof e==='string'?e:e.message).join(' ');persistStore(upsertProject(res.store,{...p,metadata:{...p.metadata,status:'listo'}}));start(res.mission.id,config.difficulty);return null}
 function removeProject(p:NormalizedProject){const r=deleteProject(store,p.id);persistStore(r.store);if(r.removedMissions.length){const gone=(x:GameState)=>r.removedMissions.includes(x.scenarioId);persist({...data,active:data.active&&gone(data.active)?null:data.active,history:data.history.filter(x=>!gone(x)),suspended:(data.suspended??[]).filter(x=>!gone(x))})}}
 const editingProject=store.projects.find(p=>p.id===editing);
 const timeRef=useRef<{id:string;phase:number;start:number}|null>(null);
 function flushTime(){const t=timeRef.current;timeRef.current=null;if(!t)return;const seconds=(Date.now()-t.start)/1000;if(seconds<2)return;setData(d=>{if(!d.active||d.active.id!==t.id||d.active.outcome)return d;const next={...d,active:act(d.active,{type:'stageTime',phase:t.phase,seconds})};try{save(next)}catch{/* timing is optional */}return next})}
 useEffect(()=>{const a=data.active;if(view!=='game'||!a||historyGame||a.outcome)return;const begin=()=>{timeRef.current={id:a.id,phase:a.phase,start:Date.now()}};begin();const onVisibility=()=>{if(document.hidden)flushTime();else if(!timeRef.current)begin()};document.addEventListener('visibilitychange',onVisibility);return ()=>{document.removeEventListener('visibilitychange',onVisibility);flushTime()}// Restart the stage timer only when the mission, its stage or its closing changes, not on every action.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[view,data.active?.id,data.active?.phase,!!data.active?.outcome,historyGame]);
 useEffect(()=>{const h=(e:Event)=>setLearn((e as CustomEvent<string>).detail||'vpn');window.addEventListener('proyecta:learn',h);return ()=>window.removeEventListener('proyecta:learn',h)},[]);
 const [pendingDrafts,setPendingDrafts]=useState(0),[briefing,setBriefing]=useState(false),[impact,setImpact]=useState<{id:number;items:string[]}|null>(null);
 useEffect(()=>{if(!impact)return;const timer=setTimeout(()=>setImpact(null),6500);return ()=>clearTimeout(timer)},[impact]);
 const g=historyGame??data.active,s=g?scenarioById(g.scenarioId):null;
 function persist(next:SaveData){setData(next);try{save(next);setStorageError('')}catch{setStorageError('No se pudo guardar en este navegador. La partida sigue en memoria; mantén esta pestaña abierta.')}}
 function storeGame(game:GameState){const history=game.outcome?[...data.history.filter(v=>v.id!==game.id),game].slice(-30):data.history;const suspended=[...(data.suspended??[]).filter(v=>v.id!==game.id),...(data.active&&!data.active.outcome&&data.active.id!==game.id?[data.active]:[])].filter((v,i,all)=>all.findIndex(x=>x.id===v.id)===i);persist({...data,suspended,active:game,history,campaign:updateCampaign(campaignSummary(data.history,data.campaign).records,game)});setHistoryGame(null)}
 function send(action:Action){if(!g)return;try{if(['next','visit'].includes(action.type)&&pendingDrafts>0)throw new Error('Confirma los cambios pendientes antes de avanzar. Busca los botones de confirmación de esta etapa.');const next=act(g,action);announceExperience(decisionMoment(g,next));if(action.type==='reflection'||action.type==='learn'||action.type==='answerV2'||action.type==='hintV2'){persist({...data,active:data.active?.id===next.id?next:data.active,history:data.history.map(v=>v.id===next.id?next:v)});if(historyGame)setHistoryGame(next);}else storeGame(next);setError('');const items:string[]=[];if(next.cash!==g.cash)items.push('Presupuesto $ '+money(available(g))+' → $ '+money(available(next)));if(next.month!==g.month)items.push('+'+(next.month-g.month)+' meses');if(next.quality!==g.quality)items.push('Información +'+(next.quality-g.quality));if(next.support!==g.support)items.push('Apoyo '+(next.support>g.support?'+':'')+(next.support-g.support));if(next.reputation!==g.reputation)items.push('Legitimidad '+(next.reputation>g.reputation?'+':'')+(next.reputation-g.reputation));{const r0=Math.round(riskLevel(g)),r1=Math.round(riskLevel(next));if(r0!==r1)items.push('Riesgo '+r0+' % → '+r1+' %');}if(next.phase!==g.phase)items.push('Nueva etapa: '+phases[next.phase]);if(!items.length&&next.journal.length>g.journal.length)items.push('Decisión registrada');if(items.length)setImpact({id:Date.now(),items});if(next.phase!==g.phase){window.scrollTo({top:0,behavior:'smooth'});setMenu(false)}return {ok:true};}catch(e){const message=e instanceof Error?e.message:'No se pudo aplicar la decisión.';announceExperience({cue:'error',title:'Revisa tu decisión',detail:message});setError(message);return {ok:false,error:message};}}
 function start(id:string,d=difficulty,code=seed,challenge?:Challenge){let game:GameState;try{game=id.startsWith('gen-')?startGeneratedGame(id,code.trim()||'PROY-4831'):createGameV2(id,d,code.trim()||'PROY-4831',mode)}catch(e){setError(e instanceof Error?e.message:String(e));return}if(challenge)game.v2!.challenge=structuredClone(challenge);storeGame(game);setView('game');setSetup(null);setBriefing(true);setError('');window.scrollTo(0,0)}
 useWebMCP(g,send);
 function goHome(){setView('home');setHistoryGame(null);setMenu(false);setError('')}
 const alerts=<>{storageError&&<div role="alert" className="toast persistent"><AlertTriangle size={18}/>{storageError}</div>}{error&&<div role="alert" className="toast"><AlertTriangle size={18}/><span>{error}</span><button className="icon-btn" aria-label="Cerrar aviso" onClick={()=>setError('')}><X size={17}/></button></div>}</>;
 if(view==='home'||view==='help'||view==='history'||view==='exam'||view==='projects'||view==='builder'||view==='import'||!g||!s)return <div className="landing aurora-home">{alerts}<header className="home-header"><a className="brand" href="#" onClick={e=>{e.preventDefault();goHome()}}>P<span>PROYECTA<small>RECONSTRUIR AURORA</small></span></a><div className="home-nav"><button onClick={()=>setView('projects')}><Home size={16}/>Mis proyectos</button><button onClick={()=>setView('help')}><BookOpen size={16}/>Cómo jugar</button><button onClick={()=>setView('history')}><History size={16}/>Resultados</button><button onClick={()=>setView('exam')}><BookOpen size={16}/>Examen 2</button><span className="pill">CONSEJO DE RECONSTRUCCIÓN</span></div></header>
 {view==='home'&&<ResetVerification games={data.history.length+(data.active?1:0)+(data.suspended??[]).length} projects={store.projects.length}/>}{view==='home'&&<HomeActions canContinue={!!data.active&&!data.active.outcome} onStory={()=>document.querySelector('.nation-home')?.scrollIntoView({behavior:'smooth'})} onImport={()=>setView('import')} onCreate={()=>openBuilder(emptyProject())} onContinue={()=>{setView('game');setHistoryGame(null)}} onLearn={()=>setLearn('formulacion')} onHow={()=>setView('help')}/>}
 {view==='home'&&<NationHome vault={data.campaign} history={data.history} active={data.active} onChoose={setSetup} onContinue={()=>{setView('game');setHistoryGame(null)}} onLearn={()=>setView('help')} role={role} setRole={setRole}/>}
 {view==='home'&&<ChallengeCatalog onStart={c=>start(c.scenarioId,c.difficulty,c.seed,c)}/>}
 {view==='home'&&(data.suspended??[]).length>0&&<Panel title="Partidas en pausa">{data.suspended!.map(saved=><Button key={saved.id} secondary onClick={()=>{storeGame(saved);setView('game')}}>Continuar {scenarioById(saved.scenarioId).title} · mes {saved.month}</Button>)}</Panel>}{view==='exam'&&<main className="reading"><Exam2 onExit={goHome}/></main>}
 {view==='projects'&&<ProjectsCenter projects={store.projects} missions={store.missions} games={[...(data.active?[data.active]:[]),...(data.suspended??[]),...[...data.history].reverse()].filter((x,i,all)=>all.findIndex(y=>y.id===x.id)===i)} onPlayOfficial={id=>setSetup(id)} onCreate={()=>openBuilder(emptyProject())} onImport={()=>setView('import')} onEdit={openBuilder} onDuplicate={p=>openBuilder(duplicateProject(p))} onDelete={removeProject} onPlayMission={id=>start(id)} onContinue={x=>{storeGame(x);setView('game')}} onForkGame={x=>{try{const copy=x.outcome?forkDecision(x):{...structuredClone(x),id:crypto.randomUUID()};storeGame(copy);setView('game')}catch(e){setError(e instanceof Error?e.message:String(e))}}} onReset={()=>setResetOpen(true)}/>}
 {view==='import'&&<ImportProject onBack={()=>setView('projects')} onOpen={openBuilder}/>}
 {view==='builder'&&editingProject&&<ProjectBuilder project={editingProject} savedAt={savedAt} onChange={p=>persistStore(upsertProject(store,p))} onExit={()=>setView('projects')} onGenerate={generate}/>}
 {view==='builder'&&!editingProject&&<main className="reading"><Panel title="Proyecto no disponible"><Button onClick={()=>setView('projects')}>Mis proyectos</Button></Panel></main>}{view==='help'&&<main className="reading"><button className="text-btn" onClick={goHome}><ArrowLeft size={16}/>Escenarios</button><h1>Aprende decidiendo.</h1><p className="lead">Construye una estrategia, observa sus consecuencias y vuelve a intentarlo.</p><HowToPlay/><Panel title="Tutorial interactivo · 3 minutos"><Tutorial/></Panel><Panel title="Centro de aprendizaje"><LearningCenter/></Panel><Panel title="Tu recorrido"><ol className="help-steps">{phases.map((p,i)=><li key={p}><strong>{p}</strong><p>{guidance[i]}</p></li>)}</ol></Panel><Panel title="Las reglas básicas"><p>Todos los montos se expresan en millones de COP (M). Contratar estudios, tratar con actores y mitigar riesgos consume recursos. Los controles exploratorios cambian la propuesta al confirmar.</p><p>Avanzar de etapa consume un mes de trabajo. Reabrir una etapa anterior cuesta un mes y 0,2 % del presupuesto inicial. Una inversión comprometida se adapta mediante decisiones de ejecución.</p><p>La semilla reproduce condiciones externas. Guarda el código y repite para comparar estrategias. La dificultad cambia lo que conoces y tu exposición, sin cambiar la realidad subyacente.</p><p>Para una sesión de 60–90 minutos: 15 de diagnóstico, 10 de formulación, 15 de preparación, 15 de evaluación, 10 de regulación y 15 de ejecución y discusión final.</p></Panel><Button onClick={()=>{setDifficulty('guiado');setSetup('agua')}}>Iniciar en modo guiado <ArrowRight size={17}/></Button></main>}
 {view==='history'&&<main><button className="text-btn" onClick={goHome}><ArrowLeft size={16}/>Escenarios</button><h1>Lo que aprendiste.</h1><p className="lead">Resultados de este navegador. Cada estrategia deja una historia distinta.</p>{!data.history.length?<Panel title="Todavía no hay resultados"><p>Completa o cierra una partida para encontrar aquí su evaluación.</p><Button onClick={goHome}>Elegir escenario</Button></Panel>:<div className="history-list">{[...data.history].reverse().map(game=><button key={game.id} onClick={()=>{setHistoryGame(game);setView('game')}}><div><span className="eyebrow">{game.seed} · {game.difficulty}</span><h3>{scenarioById(game.scenarioId).title}</h3><p>{selected(game)?.name} · {game.outcome?.status}</p></div><strong>{game.outcome?.score}<small>/100</small></strong><ChevronRight size={20}/></button>)}</div>}</main>}
 <footer><span>Datos utilizados con fines académicos y de simulación.</span><span>PROYECTA 2.4.4 · Guardado en este navegador</span></footer>
 {resetOpen&&<Modal title="Restablecer partidas" onClose={()=>setResetOpen(false)}><ResetDialog onClose={()=>setResetOpen(false)}/></Modal>}{learn&&<Modal title="Centro de aprendizaje" onClose={()=>setLearn(null)} wide><LearningCenter key={learn} focus={learn}/></Modal>}
 {setup&&<Modal title="Tu siguiente decisión empieza aquí." onClose={()=>setSetup(null)}><div className="eyebrow">NUEVA SIMULACIÓN</div><Field label="Escenario y rol"><select value={setup} onChange={e=>setSetup(e.target.value)}>{scenarios.map(s=><option value={s.id} key={s.id}>{s.regulator?'Regulador':s.role==='publico'?'Público':'Privado'} · {s.title}</option>)}</select></Field><MissionProfileCard id={setup}/><DifficultyGuide value={difficulty} onChange={setDifficulty}/><ModeChoice value={mode} onChange={setMode}/><Field label="Código de condiciones iniciales" hint="Usa el mismo código para comparar estrategias."><input value={seed} maxLength={40} onChange={e=>setSeed(e.target.value)}/></Field>{data.active&&!data.active.outcome&&<p className="notice">La partida actual quedará en pausa y podrás retomarla desde el inicio.</p>}<Button onClick={()=>start(setup)}>Entrar a la simulación <ArrowRight size={17}/></Button></Modal>}
 </div>;

 return <div className={"game-shell"+(stagesHidden?" stages-hidden":"")}>{alerts}{impact&&<div className="impact-toast" role="status" key={impact.id}><span>CONSECUENCIAS DE TU DECISIÓN</span><div>{impact.items.map(item=><strong key={item}>{item}</strong>)}</div></div>}<header className="game-header"><button className="icon-btn mobile-menu" aria-label="Abrir etapas" onClick={()=>setMenu(!menu)}><Menu/></button><button className="stages-toggle" aria-pressed={!stagesHidden} aria-label={stagesHidden?"Mostrar el menú de etapas":"Ocultar el menú de etapas"} title={stagesHidden?"Mostrar etapas":"Ocultar etapas para ampliar la vista"} onClick={()=>{const v=!stagesHidden;setStagesHidden(v);saveStagesHidden(v)}}>{stagesHidden?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>}<span>{stagesHidden?"Etapas":"Ocultar"}</span></button><button className="game-brand" onClick={goHome}>P<span>PROYECTA</span></button><div className="game-title">{s.sector}<small>{s.regulator?'Regulador':s.role==='publico'?'Decisor público':'Decisor privado'} · {g.difficulty}</small></div><span className="game-code">{g.seed}</span><button className="icon-btn" aria-label="Volver al inicio" onClick={goHome}><Home size={19}/></button></header><ResourceDeck key={g.id} g={g}/>
 <aside className={'sidebar '+(menu?'open':'')}><div className="eyebrow">PLAN DE RECONSTRUCCIÓN</div><nav>{phases.map((phase,i)=><button className={(i===g.phase?'active ':'')+(i<g.phase?'done':'')} key={phase} disabled={i>(g.v2?g.maxPhase:g.phase)||!!g.snapshot||!!g.outcome||i===g.phase} onClick={()=>g.v2?send({type:'visit',phase:i}):setReopen(i)}><span>{i<g.phase?'✓':String(i+1).padStart(2,'0')}</span>{phase}{i===g.phase&&<ChevronRight size={16}/>}</button>)}</nav><div className="sidebar-bottom"><button onClick={()=>setJournal(true)}><History size={17}/>Bitácora <span>{g.journal.length}</span></button><button onClick={()=>setLearn('vpn')}><BookOpen size={17}/>Centro de aprendizaje</button>{!g.outcome&&<button className="abandon-link" onClick={()=>setAbandon(true)}>Cerrar / abandonar partida</button>}<small>Datos simulados · COP en millones</small><span className="save-indicator"><i/>{storageError?'Partida en memoria':'Guardado local'}</span></div></aside>
 <main className="game-main"><div className="page-heading"><div className="eyebrow">ETAPA {String(g.phase+1).padStart(2,'0')} DE 08 · {phases[g.phase].toUpperCase()}</div><h1>{headings[g.phase]}</h1><p>{missions[g.scenarioId].district}{g.scenarioId.startsWith('gen-')?'':' · Aurora'} <span>·</span> Mes {g.month}</p></div><div className="phase-strip">{phases.map((p,i)=><span key={p} title={p} className={i<=g.phase?'filled':''}/>)}</div><div className="mobile-advisor"><Advisor g={g}/></div><ChallengeStatus g={g}/><ProjectMap g={g} send={send}/><DilemmaPanel key={g.v2?.pendingDilemma??"none"} g={g} send={send}/><StageGuide g={g} pending={pendingDrafts}/><DraftProvider key={g.id+':'+g.phase+':'+(g.v2?.resetCount??0)} onChange={setPendingDrafts}><div className="phase-content"><details className="practice-drawer"><summary>Entrenar conceptos · práctica opcional</summary><><PracticeV2 key={g.id+g.phase} g={g} send={send}/></></details><SectionNavigator phase={g.phase}>{g.phase===0&&<Diagnosis g={g} send={send}/>} {g.phase===1&&<Formulation g={g} send={send}/>} {g.phase===2&&<Preparation g={g} send={send}/>} {g.phase===3&&<Evaluation g={g} send={send}/>} {g.phase===4&&<Regulation g={g} send={send}/>} {g.phase===5&&<Decision g={g} send={send}/>} {g.phase===6&&<Execution g={g} send={send}/>} {g.phase===7&&g.outcome&&<Results g={g} history={data.history} onRetry={()=>start(g.scenarioId,g.difficulty,g.seed,g.v2?.challenge)} onFork={()=>{try{storeGame(forkDecision(g));setHistoryGame(null);window.scrollTo(0,0)}catch(e){setError(String(e))}}}/> }{g.phase!==6&&<MgaLab g={g} send={send}/>}</SectionNavigator>{g.phase<5&&<Next onClick={()=>send({type:'next'})}/>}</div></DraftProvider><footer className="game-footer">Datos utilizados con fines académicos y de simulación.</footer></main>
 <aside className="context-panel"><PinnedAlternative g={g}/><Advisor g={g}/><CommandCenter g={g} send={send}/><span className="eyebrow">EL DISTRITO TE NECESITA</span><Panel title="Tu encargo"><p>{s.nodes[0].objective}</p><div className="context-stat"><span>Fondo inicial de esta partida</span><strong>$ {money(g.v2?.initialCash??s.budget)}</strong></div><div className="context-stat"><span>Comprometido</span><strong>$ {money(g.committed)}</strong></div><div className="context-stat"><span>Ejecutado / gastado</span><strong>$ {money(g.spent)}</strong></div><div className="context-stat"><span>Deuda y socios</span><strong>$ {money(g.loans.reduce((n,l)=>n+l.principal,0))}</strong></div></Panel>{g.difficulty==='guiado'&&<Panel title="Una pausa para pensar" className="coaching"><BookOpen size={20}/><p>{guidance[g.phase]}</p></Panel>}<Panel title="Última consecuencia">{g.journal.length?<><span className="eyebrow">MES {g.journal.at(-1)!.month}</span><p>{g.journal.at(-1)!.title}</p><small>{g.journal.at(-1)!.detail}</small></>:<p>Todo empieza con entender el problema.</p>}</Panel><details className="context-details"><summary>Recordar el principio del juego</summary><p>Elige la mejor alternativa posible dadas tus restricciones, información, riesgos e incentivos.</p></details></aside>
 {briefing&&<Modal title="El Consejo tiene un encargo para ti." onClose={()=>setBriefing(false)} wide><MissionBriefing g={g} onAccept={()=>setBriefing(false)}/></Modal>}
 {learn&&<Modal title="Centro de aprendizaje" onClose={()=>setLearn(null)} wide><LearningCenter key={learn} focus={learn}/></Modal>}{journal&&<Modal title="Bitácora del proyecto" onClose={()=>setJournal(false)} wide><ConsequenceLog g={g}/>{g.journal.length?<Journal g={g}/>:<p>Aquí aparecerán tus decisiones y consecuencias.</p>}</Modal>}
 {reopen!==null&&<Modal title={'Reabrir '+phases[reopen]} onClose={()=>setReopen(null)}><p>Reformular consume un mes y $ {money(s.budget*.002)}. Tendrás que revisar las etapas posteriores y confirmar nuevamente la evaluación.</p><div className="actions"><Button secondary onClick={()=>setReopen(null)}>Cancelar</Button><Button onClick={()=>{send({type:'reopen',phase:reopen});setReopen(null)}}>Reabrir etapa</Button></div></Modal>}
 {abandon&&<Modal title="¿Cerrar esta estrategia?" onClose={()=>setAbandon(false)}><p>Se liberarán compromisos pendientes y se conservarán los gastos realizados. Recibirás una evaluación con las lecciones de esta trayectoria.</p><div className="actions"><Button secondary onClick={()=>setAbandon(false)}>Seguir jugando</Button><Button onClick={()=>{send({type:'abandon'});setAbandon(false)}}>Cerrar y evaluar</Button></div></Modal>}
 </div>;
}





import {createGameV2} from './domain/engine';
import {ProjectMap,CommandCenter,PinnedAlternative} from './features/CommandCenter';
import PracticeV2 from './features/PracticeV2';
import {DilemmaPanel,ConsequenceLog} from './features/Dilemmas';
import DifficultyGuide from './features/DifficultyGuide';
import LearningCenter from './features/v22/LearningCenter';
import { HowToPlay, Tutorial } from './features/v22/HowToPlay';
import { MissionProfileCard, ModeChoice } from './features/v22/SetupExtras';
import Exam2 from './features/v22/Exam2';
import ProjectsCenter from './features/projects/ProjectsCenter';
import ProjectBuilder from './features/projects/ProjectBuilder';
import ImportProject from './features/projects/ImportProject';
import HomeActions from './features/projects/HomeActions';
import {ResetDialog,ResetVerification} from './features/projects/ResetDialog';
import {activateStore,createMission,deleteProject,loadStore,saveStore,startGeneratedGame,upsertProject,type ProjectStore} from './domain/project/store';
import {duplicateProject,emptyProject} from './domain/project/project';
import type {MissionConfig,NormalizedProject} from './domain/project/types';

/** Stage menu visibility during a game: a per-browser convenience (wider work area), never part of the game. */
const stagesKey='proyecta-stages-hidden-v1';
function readStagesHidden(){try{return localStorage.getItem(stagesKey)==='1'}catch{return false}}
function saveStagesHidden(v:boolean){try{localStorage.setItem(stagesKey,v?'1':'0')}catch{/* storage blocked: lasts for this session */}}
